name: Shell Commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: echo name
        run: echo "Welcome Ayaz"
      - name: echo hostname
        run: echo "$(hostname)"
      - name: multiline script
        run: |
          node -v
          npm -v  

