name: Actions Workflow

on:
  push:
  # push:
  #   branches:
  #     - main
  #     - "feature/*"   # feature/A feature/B  not for feature/A/B
  #     - "feature/**"  # feature/A feature/B feature/A/B
  #     - "!feature/C"  # Ignore feature/C
  #   tags:
  #     - v1.*
  #     - v2
  #   paths:
  #     - "**.js"        # when you push a js file
  #     - "!filename.js" # Ignore filename.js file

  repository_dispatch:
    types: [build]
  # schedule:
  #  - cron: '0/5 * * * *'
    
  #push:
  #pull_request:
  #  types: [closed, assigned, opened, reopened]

jobs:
  run-github-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: PayLoad
        run: echo "${{ github.event.client_payload.env }}"
      - name: List Files
        run: |
          pwd
          ls -a 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{github.token}}"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch history for all tags and branches
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  
      - name: List Files after Checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Ayaz
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"